### ISSUE TITLE
Invalid D200 errors

### ISSUE THREAD

**Issue by playpauseandstop** [GreenSteam/pep257#105]
I got strange D200 errors when docstring cannot be one-liner.

For example,

        def clean(self):
            """
            Remove provider and provider hotel from form data if it not supplied.
            """

will produce D200 error.

But if change it to one-liner, like:

        def clean(self):
            """Remove provider and provider hotel from form data if it not supplied."""

the line with docstring obviously would be longer than 79 characters, so I get ``E501 line too long (83 > 79 characters)`` error.

**Comment by Nurdok** [comment]
I don't think the error is invalid. You should shorten your one line description. If you can't do it without missing since information, add a body to your docstring with details.

**Comment by OddBloke** [comment]
I don't feel particularly strongly about it, but this resolution seems wrong to me. This docstring is totally reasonable:

```
"""
Pretend this is super long
"""
```

and it's only three lines whereas the minimum possible multi-line docstring is five:

```
"""
Slightly shorter

Tiny amount of detail.
"""
```.

One line would be best, but three is still better than five.

**Comment by Nurdok** [comment]
I don't agree that fewer lines is always better. A long line means a long sentence. Several lines means you've broken the first and primary description of the defintiion into a small, readable and understandable idea.

**Comment by sigmavirus24** [comment]
I tend to agree with @Nurdok. I've found that this constrains me to creating a concise description and adding good detail to a body. In most cases, I'm documenting the parameters anyway, so adding a body is not a problem.

Instead of trying to force the tool to accept your style preferences, configure the tool to ignore what you don't like.

**Comment by OddBloke** [comment]
On Sun, Aug 06, 2017 at 05:47:18AM -0700, Ian Stapleton Cordasco wrote:
> I tend to agree with @Nurdok. I've found that this constrains me to creating a concise description and adding good detail to a body. In most cases, I'm documenting the parameters anyway, so adding a body is not a problem.

On further consideration, I think I've come around as well.  I misparsed
the error message ("One-line docstring should fit on one line with
quotes") as telling me that I'd mistakenly wrapped something that could
currently fit on one line across three lines (rather than it telling me
that I should shorten it).  With that latter reading, this warning
doesn't make sense, but with the former (correct), it does.

> Instead of trying to force the tool to accept your style preferences, configure the tool to ignore what you don't like.

Yep, my initial assumption was that this was the tool not understanding
line lengths (which wouldn't necessarily be fixable just through
configuration), but I see now that this is not the case. :-)

Thanks to you both for taking the time to respond!

**Comment by Nurdok** [comment]
@OddBloke, no problem!
