### ISSUE TITLE
Nested classes and functions are not checked

### ISSUE THREAD

**Issue by JensRantil** [GreenSteam/pep257#13]
If I check a file containing

```python
class A:

    """Test documentation."""

    class B:
        pass
```

I notice that it will not complain that `B` does not contain any PyDoc. I guess this is incorrect behaviour?

**Comment by Nurdok** [comment]
My two cents on this issue:

Nested classes are public. They are public because names defined inside a class definitions are accessible from outside of the class, such as methods, class methods, class members, etc. For all of these, we consider them public unless they are prepended with an underscore.

Nested function are private. They are private because names inside a function definitions are not accessible from the outside, namely local variables.

**Comment by Nurdok** [comment]
Just to make it clear - in "nested class" I meant a class inside a class, not a class inside a function.
